### ISSUE TITLE
Checklist: Create guides for the Settings menu

### ISSUE THREAD

**Issue by Soitora** [tachiyomiorg/website#24]
# Settings
## General
- [x] Language
- [x] Application theme
- [x] Library manga per row
- [x] Start screen
- [x] Library update frequency
- [x] Library update restrictions
- [x] Only update ongoing manga
- [x] Categories to include in global update
- [x] Library update order
- [x] Default category
## Reader
- [x] Default viewer
- [x] Scale type
- [x] Zoom start position
- [x] Rotation
- [x] Background color
- [x] Double tap animation speed
- [x] Skip chapters marked read
- [x] Fullscreen
- [x] Keep screen on
- [x] Show page number
- [x] 32-bit color
#### Pager
- [x] Page transitions
- [x] Crop borders
#### Navigation
- [x] Tapping
- [x] Long tap dialog
- [x] Volume keys
- [x] Invert volume keys
## Downloads
- [x] Downloads directory
- [x] Only download over Wi-Fi
#### Remove after read
- [x] Remove when marked as read
- [x] Remove after read
#### Download new chapters
- [x] Download new chapters
- [x] Categories to include in download
## Tracking
- [x] Sync chapters after reading
#### Services
Explain services?
## Backup
- [x] Create backup
- [x] Restore backup
#### Service
- [x] Backup frequency
- [x] Backup directory
- [x] Mac automatic backups
## Advanced
- [x] Clear chapter cache
- [x] Clear cookies
- [x] Clear database
- [x] Refresh library metadata
- [x] Refresh tracking metadata

**Comment by arkon** [comment]
Before anyone starts on this, I want to point out that having a guide for everything is overkill.

If it can be made more intuitive within the app itself, effort should go towards that, not patching over the actual root issues.

**Comment by joseph619** [comment]
Yeah but the app itself isn't changing anytime soon, 1.x is still far away

**Comment by arkon** [comment]
Minor usability changes are still accepted in 0.x.

**Comment by Soitora** [comment]
It could be more of a manual and not a guide, I don't know, it's up to the people adding it

**Comment by joseph619** [comment]
Reader, advanced and tracking are completed, I think we're done for this?
